#!/usr/bin/env bash

# This how I install watch-markdown on Pop!_OS 22.04 (derived from Ubuntu 22.04).

set -e

if ! ( which falkon && which pandoc ) >/dev/null ; then
    sudo apt install -y falkon pandoc
fi

(
    this_dir=$(pwd)
    cd "$HOME/.local/bin"
    ln -sf "$this_dir/watch-markdown" .
    ln -sf "$this_dir/watch-markdown-gui" .
)

# Install 'entr'. The apt package is from 2021, has problems like -z doesn't work.
# So install from source.
version="5.3"
if ! ( which entr >/dev/null && [ "$(entr 2>&1 | grep release | cut -d' ' -f2)" = "$version" ] );  then
    (
    cd /tmp
    wget "http://eradman.com/entrproject/code/entr-${desired}.tar.gz"
    tar -xzf "entr-${version}.tar.gz"
    cd "entr-$version"
    ./configure
    sudo make install
    rm -rf "/tmp/entr-${version}*"
    )
fi

config="$HOME/.config/watch-markdown"
mkdir -p "$config"
cp style.css "$config"

desktop-file-install --dir="$HOME/.local/share/applications/" watch-markdown-gui.desktop

