#!/usr/bin/env bash

# This how I install watch-markdown on Pop!_OS 22.04 (derived from Ubuntu 22.04).

set -e

sudo apt install -y entr falkon pandoc

(
    this_dir=$(pwd)
    cd "$HOME/.local/bin"
    ln -sf "$this_dir/watch-markdown" .
    ln -sf "$this_dir/watch-markdown-gui" .
)

config="$HOME/.config/watch-markdown"
mkdir -p "$config"
cp style.css "$config"

desktop-file-install --dir="$HOME/.local/share/applications/" watch-markdown-gui.desktop

