#!/usr/bin/env bash

set -e

# We no longer need the packages that 'install' apt-installed,
# but don't automatically remove them since the user may have had them
# installed beforehand.

rm -f ~/.local/bin/watch-markdown
rm -f ~/.local/bin/watch-markdown-gui
rm -fr ~/.config/watch-markdown
rm -f ~/.local/share/applications/watch-markdown-gui.desktop

