#!/usr/bin/env bash

set -e

# We no longer need the packages that 'install' apt-installed,
# but don't automatically remove them since the user may have had them
# installed beforehand.

rm ~/.local/bin/watch-markdown
rm -r ~/.config/watch-markdown
rm ~/.local/share/applications/watch-markdown.desktop

