#!/usr/bin/env bash

# A wrapper for invoking watch-markdown from the Gnome GUI. This exists so that
# we can redirect all output to a log file, because I suspect that stdout/err
# does not exist on scripts launched from the GUI, so processes are getting
# wedged after filling the output buffers.

# Redirect both stdout and stderr
logdir="$HOME/.local/var/log"
mkdir -p "$logdir"
watch-markdown "$@" >"$logdir/watch-markdown.log" 2>&1

